export const getShipments = () => [
  {
    waybill: "203481267",
    status: "In Transit",
    requestedPickupDate: "2021-02-19",
    requestedPickupTimeSlot: {
      startTime: "08:30am",
      endTime: "09:30am",
    },
    pickupAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    pickupPOC: {
      name: "Siby Mathew",
      email: "siby@pikkol.com",
      phoneNumber: "98545454455",
    },
    requestedDeliveryDate: "2021-02-19",
    requestedDeliveryTimeSlot: {
      startTime: "08:00am",
      endTime: "09:00am",
    },
    deliveryAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    deliveryPOC: {
      name: "Jayaram Kasi",
      email: "jayaram@pikkol.com",
      phoneNumber: "9875457890",
    },
    shipmentType: "forward",
    shipmentTatCriterion: "none",
    handoverMode: "pickup",
    noOfBoxes: 0,
    paymentInfo: {
      paymentMode: "Prepaid",
      totalAmount: "string",
      collectableAmount: "string",
      currencyCode: "INR",
    },
    isFragile: false,
    reversePickupInfo: {
      reason: "Wrong product",
      qc_question_1: "Is it soiled?",
      return_product_label: "RTN011123",
    },
    clientOrderInfo: {
      orderID: "BLL12322",
      orderDate: "27-04-2018",
      channel: "website",
    },
    handlingInfo: {
      weight: "1.4 kg",
      length: "23cm",
      breadth: "20 cm",
    },
    whatsappOptin: true,
    customData: {
      type: "ecommerce",
    },
    createdAt: "2021-02-19T06:10:08.661Z",
    createdBy: "23",
  },
  {
    waybill: "203481267",
    status: "In Transit",
    requestedPickupDate: "2021-02-19",
    requestedPickupTimeSlot: {
      startTime: "08:30am",
      endTime: "09:30am",
    },
    pickupAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    pickupPOC: {
      name: "Siby Mathew",
      email: "siby@pikkol.com",
      phoneNumber: "98545454455",
    },
    requestedDeliveryDate: "2021-02-19",
    requestedDeliveryTimeSlot: {
      startTime: "08:00am",
      endTime: "09:00am",
    },
    deliveryAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    deliveryPOC: {
      name: "Jayaram Kasi",
      email: "jayaram@pikkol.com",
      phoneNumber: "9875457890",
    },
    shipmentType: "forward",
    shipmentTatCriterion: "none",
    handoverMode: "pickup",
    noOfBoxes: 0,
    paymentInfo: {
      paymentMode: "Prepaid",
      totalAmount: "string",
      collectableAmount: "string",
      currencyCode: "INR",
    },
    isFragile: false,
    reversePickupInfo: {
      reason: "Wrong product",
      qc_question_1: "Is it soiled?",
      return_product_label: "RTN011123",
    },
    clientOrderInfo: {
      orderID: "BLL12322",
      orderDate: "27-04-2018",
      channel: "website",
    },
    handlingInfo: {
      weight: "1.4 kg",
      length: "23cm",
      breadth: "20 cm",
    },
    whatsappOptin: true,
    customData: {
      type: "ecommerce",
    },
    createdAt: "2021-02-19T06:10:08.661Z",
    createdBy: "23",
  },
  {
    waybill: "203481267",
    status: "In Transit",
    requestedPickupDate: "2021-02-19",
    requestedPickupTimeSlot: {
      startTime: "08:30am",
      endTime: "09:30am",
    },
    pickupAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    pickupPOC: {
      name: "Siby Mathew",
      email: "siby@pikkol.com",
      phoneNumber: "98545454455",
    },
    requestedDeliveryDate: "2021-02-19",
    requestedDeliveryTimeSlot: {
      startTime: "08:00am",
      endTime: "09:00am",
    },
    deliveryAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    deliveryPOC: {
      name: "Jayaram Kasi",
      email: "jayaram@pikkol.com",
      phoneNumber: "9875457890",
    },
    shipmentType: "forward",
    shipmentTatCriterion: "none",
    handoverMode: "pickup",
    noOfBoxes: 0,
    paymentInfo: {
      paymentMode: "Prepaid",
      totalAmount: "string",
      collectableAmount: "string",
      currencyCode: "INR",
    },
    isFragile: false,
    reversePickupInfo: {
      reason: "Wrong product",
      qc_question_1: "Is it soiled?",
      return_product_label: "RTN011123",
    },
    clientOrderInfo: {
      orderID: "BLL12322",
      orderDate: "27-04-2018",
      channel: "website",
    },
    handlingInfo: {
      weight: "1.4 kg",
      length: "23cm",
      breadth: "20 cm",
    },
    whatsappOptin: true,
    customData: {
      type: "ecommerce",
    },
    createdAt: "2021-02-19T06:10:08.661Z",
    createdBy: "23",
  },
  {
    waybill: "203481267",
    status: "In Transit",
    requestedPickupDate: "2021-02-19",
    requestedPickupTimeSlot: {
      startTime: "08:30am",
      endTime: "09:30am",
    },
    pickupAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    pickupPOC: {
      name: "Siby Mathew",
      email: "siby@pikkol.com",
      phoneNumber: "98545454455",
    },
    requestedDeliveryDate: "2021-02-19",
    requestedDeliveryTimeSlot: {
      startTime: "08:00am",
      endTime: "09:00am",
    },
    deliveryAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    deliveryPOC: {
      name: "Jayaram Kasi",
      email: "jayaram@pikkol.com",
      phoneNumber: "9875457890",
    },
    shipmentType: "forward",
    shipmentTatCriterion: "none",
    handoverMode: "pickup",
    noOfBoxes: 0,
    paymentInfo: {
      paymentMode: "Prepaid",
      totalAmount: "string",
      collectableAmount: "string",
      currencyCode: "INR",
    },
    isFragile: false,
    reversePickupInfo: {
      reason: "Wrong product",
      qc_question_1: "Is it soiled?",
      return_product_label: "RTN011123",
    },
    clientOrderInfo: {
      orderID: "BLL12322",
      orderDate: "27-04-2018",
      channel: "website",
    },
    handlingInfo: {
      weight: "1.4 kg",
      length: "23cm",
      breadth: "20 cm",
    },
    whatsappOptin: true,
    customData: {
      type: "ecommerce",
    },
    createdAt: "2021-02-19T06:10:08.661Z",
    createdBy: "23",
  },
  {
    waybill: "203481267",
    status: "In Transit",
    requestedPickupDate: "2021-02-19",
    requestedPickupTimeSlot: {
      startTime: "08:30am",
      endTime: "09:30am",
    },
    pickupAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    pickupPOC: {
      name: "Siby Mathew",
      email: "siby@pikkol.com",
      phoneNumber: "98545454455",
    },
    requestedDeliveryDate: "2021-02-19",
    requestedDeliveryTimeSlot: {
      startTime: "08:00am",
      endTime: "09:00am",
    },
    deliveryAddress: {
      latitude: 0,
      longitude: 0,
      address: "string",
      doorno: "string",
      building: "string",
      postalCode: "string",
      googlePlaceId: "string",
      city: "string",
      state: "string",
      country: "string",
    },
    deliveryPOC: {
      name: "Jayaram Kasi",
      email: "jayaram@pikkol.com",
      phoneNumber: "9875457890",
    },
    shipmentType: "forward",
    shipmentTatCriterion: "none",
    handoverMode: "pickup",
    noOfBoxes: 0,
    paymentInfo: {
      paymentMode: "Prepaid",
      totalAmount: "string",
      collectableAmount: "string",
      currencyCode: "INR",
    },
    isFragile: false,
    reversePickupInfo: {
      reason: "Wrong product",
      qc_question_1: "Is it soiled?",
      return_product_label: "RTN011123",
    },
    clientOrderInfo: {
      orderID: "BLL12322",
      orderDate: "27-04-2018",
      channel: "website",
    },
    handlingInfo: {
      weight: "1.4 kg",
      length: "23cm",
      breadth: "20 cm",
    },
    whatsappOptin: true,
    customData: {
      type: "ecommerce",
    },
    createdAt: "2021-02-19T06:10:08.661Z",
    createdBy: "23",
  },
];

export const getShipmentByWaybillNumber = waybillNumber => ({
  waybill: waybillNumber,
  status: "In Transit",
  requestedPickupDate: "24 December 2020",
  requestedPickupTimeSlot: {
    startTime: "08:30am",
    endTime: "09:30am",
  },
  pickupAddress: {
    latitude: 0,
    longitude: 0,
    address: "50th Avenue Road Lake Town 78090",
    doorno: "130",
    building: "string",
    postalCode: "78903",
    googlePlaceId: "string",
    city: "string",
    state: "string",
    country: "string",
  },
  pickupPOC: {
    name: "Siby Mathew",
    email: "siby@pikkol.com",
    phoneNumber: "98545454455",
  },
  requestedDeliveryDate: "26 December 2020",
  requestedDeliveryTimeSlot: {
    startTime: "08:00am",
    endTime: "09:00am",
  },
  deliveryAddress: {
    latitude: 0,
    longitude: 0,
    address: "50th Avenue Road Lake Town 78090",
    doorno: "string",
    building: "string",
    postalCode: "789202",
    googlePlaceId: "string",
    city: "string",
    state: "string",
    country: "string",
  },
  deliveryPOC: {
    name: "Jayaram Kasi",
    email: "jayaram@pikkol.com",
    phoneNumber: "9875457890",
  },
  shipmentType: "forward",
  shipmentTatCriterion: "none",
  handoverMode: "pickup",
  noOfBoxes: 3,
  paymentInfo: {
    paymentMode: "Prepaid",
    totalAmount: "string",
    collectableAmount: "string",
    currencyCode: "INR",
  },
  isFragile: false,
  reversePickupInfo: {
    reason: "Wrong product",
    qc_question_1: "Is it soiled?",
    return_product_label: "RTN011123",
  },
  clientOrderInfo: {
    orderID: "BLL12322",
    orderDate: "27-04-2018",
    channel: "website",
  },
  handlingInfo: {
    weight: "1.4 kg",
    length: "23cm",
    breadth: "20 cm",
  },
  whatsappOptin: true,
  customData: {
    type: "ecommerce",
  },
  createdAt: "2021-02-10T06:24:41.235Z",
  createdBy: "23",
});

export const updateShipment = payload => ({ payload });

export const cancelShipment = waybillNumber => ({});

export const createShipment = payload => ({ shipment: 1 });

export const getBoxes = waybillNumber => [
  {
    label: "PKL99088887712",
    scanCode: "PKL99088887712",
    sequenceNumber: 1,
    labelPdfUrl: "https://wb.pikkol.com/label/PKL99088887712",
    customData: {
      fragile: "true",
      "wooden crating": "true",
    },
    createdAt: "2021-02-11T20:59:11.508Z",
    createdBy: "23",
  },
  {
    label: "PKL99088887712",
    scanCode: "PKL99088887712",
    sequenceNumber: 2,
    labelPdfUrl: "https://wb.pikkol.com/label/PKL99088887712",
    customData: {
      fragile: "true",
      "wooden crating": "true",
    },
    createdAt: "2021-02-11T20:59:11.508Z",
    createdBy: "23",
  },
  {
    label: "PKL99088887712",
    scanCode: "PKL99088887712",
    sequenceNumber: 3,
    labelPdfUrl: "https://wb.pikkol.com/label/PKL99088887712",
    customData: {
      fragile: "true",
      "wooden crating": "true",
    },
    createdAt: "2021-02-11T20:59:11.508Z",
    createdBy: "23",
  },
];

export const getItems = waybillNumber => [
  {
    id: 3345,
    itemCode: "SF2341188",
    uniqueSerialNumber: "SLNO178882434",
    name: "Emily Fabric Sofa",
    description: "3 seater fabric sofa in beige",
    quantity: 1,
    customData: {
      type: "personal",
      gst_applicable: "nill",
      valuation: "Rs.2500",
    },
    createdAt: "2021-02-11T21:06:15.906Z",
    createdBy: "23",
  },
  {
    id: 3346,
    itemCode: "SF2341188",
    uniqueSerialNumber: "SLNO178882434",
    name: "Emily Fabric Sofa",
    description: "3 seater fabric sofa in beige",
    quantity: 1,
    customData: {
      type: "personal",
      gst_applicable: "nill",
      valuation: "Rs.2500",
    },
    createdAt: "2021-02-11T21:06:15.906Z",
    createdBy: "23",
  },
  {
    id: 3347,
    itemCode: "SF2341188",
    uniqueSerialNumber: "SLNO178882434",
    name: "Emily Fabric Sofa",
    description: "3 seater fabric sofa in beige",
    quantity: 1,
    customData: {
      type: "personal",
      gst_applicable: "nill",
      valuation: "Rs.2500",
    },
    createdAt: "2021-02-11T21:06:15.906Z",
    createdBy: "23",
  },
];
