export const DraftManifestTypes = {
  ADD_TO_DMANIFEST: "ADD_TO_DMANIFEST",
  REMOVE_FROM_DMANIFEST: "REMOVE_FROM_DMANIFEST",
  CLEAR_DMANIFEST: "CLEAR_DMANIFEST",
  TOGGLE_DMANIFEST: "TOGGLE_DMANIFEST",
};
