export const DraftManifestTypes = {
  ADD_TO_DRAFTMANIFEST: "ADD_TO_DRAFTMANIFEST",
  REMOVE_FROM_DRAFTMANIFEST: "REMOVE_FROM_DRAFTMANIFEST",
  CLEAR_DRAFTMANIFEST: "CLEAR_DRAFTMANIFEST",
  TOGGLE_DRAFTMANIFEST: "TOGGLE_DRAFTMANIFEST",
};
